/* Отраслевые лендинги (industries-*.html): то, чего нет в solutions.js.
   Появление блоков, счётчик разделов и форма — в solutions.js, он подключён раньше. */
(window.i18n ? window.i18n.ready : Promise.resolve()).then(() => {
  'use strict';
  /* i18n:ru begin (generated by tools/i18n/embed.mjs from i18n/ru.json: the Russian text of the messages this script shows; do not edit) */
  const RU = (() => {
    const nf = new Intl.NumberFormat('ru', { useGrouping: 'always' });
    const n = (x, d) => (d === undefined ? nf : new Intl.NumberFormat('ru', { useGrouping: 'always', minimumFractionDigits: d, maximumFractionDigits: d })).format(x);
    return {
      n,
      m: {
        'js.industry.area': (v) => `${n(v.n)} м²`,
        'industries.common.calc.months': (v) => `≈ ${v.n} мес`,
        'js.industry.notPaying': () => 'Не окупается при этих условиях, разберём на аудите',
        'industries.common.calc.millions': (v) => `≈ ${n(v.n, 1)} млн ₽`,
      },
    };
  })();
  // N: a number as the site writes it in the current language; t: a message, English from the dictionary, else Russian from RU
  const N = (x, d) => (i18n.n || RU.n)(x, d);
  const t = (key, v) => { const s = i18n.t(key, v); return s === undefined ? RU.m[key](v) : s; };
  /* i18n:ru end */

  const reduce = matchMedia('(prefers-reduced-motion: reduce)').matches;

  // ---------- Направление в форме по якорю ----------
  // Пришли по ссылке на направление (#delivery) — оно выбрано в форме, и в заявку уходит source с якорем.
  const form = document.getElementById('lead-form');
  const select = form && form.elements.namedItem('direction');
  if (form && select) {
    const base = form.dataset.source;
    const sync = () => {
      const anchor = decodeURIComponent(location.hash.slice(1));
      if (!anchor || ![...select.options].some((o) => o.value === anchor)) return;
      select.value = anchor;
      form.dataset.source = `${base}#${anchor}`;
    };
    sync();
    addEventListener('hashchange', sync);
    select.addEventListener('change', () => {
      form.dataset.source = select.value ? `${base}#${select.value}` : base;
    });
  }

  // ---------- Маршрут по клинике: без анимации при reduced motion ----------
  const route = document.querySelector('.route__svg');
  if (route && reduce && route.pauseAnimations) route.pauseAnimations();

  // ---------- Мини-калькулятор уборки (модель roi-model.js) ----------
  const calc = document.querySelector('[data-calc]');
  if (!calc || !window.ROI) return;
  const { TYPES, calc: compute } = window.ROI;
  const area = calc.querySelector('#calc-area');
  const out = (k) => calc.querySelector(`[data-out="${k}"]`);
  const radios = (name) => [...calc.querySelectorAll(`input[name="${name}"]`)];
  const checked = (name) => radios(name).find((r) => r.checked).value;

  // Склад не убирают в одну смену (как в модели): прячем недоступные режимы
  const syncModes = (type) => {
    const allowed = TYPES[type].modes;
    radios('calc-mode').forEach((r) => {
      const ok = !allowed || allowed.includes(r.value);
      r.disabled = !ok;
      r.closest('.seg__o').hidden = !ok;
    });
    if (radios('calc-mode').find((r) => r.checked).disabled) {
      radios('calc-mode').find((r) => r.value === TYPES[type].mode0).checked = true;
    }
  };

  const render = () => {
    const type = checked('calc-type');
    const a = Number(area.value);
    const r = compute({ type, area: a, mode: checked('calc-mode') });
    const areaText = t('js.industry.area', { n: a });
    out('area').textContent = areaText;
    area.setAttribute('aria-valuetext', areaText);
    out('payback').textContent = Number.isFinite(r.payback)
      ? t('industries.common.calc.months', { n: Math.round(r.payback) })
      : t('js.industry.notPaying');
    out('net').textContent = t('industries.common.calc.millions', { n: +(r.net / 1e6).toFixed(1) });
    out('link').href = `roi.html?t=${type}&a=${r.area}&m=${r.mode}`;
  };

  calc.addEventListener('change', (e) => {
    if (e.target.name === 'calc-type') {
      const ty = TYPES[e.target.value];
      area.min = ty.area[0];
      area.max = ty.area[1];
      area.value = ty.area0;
      radios('calc-mode').find((r) => r.value === ty.mode0).checked = true;
      syncModes(e.target.value);
    }
    render();
  });
  area.addEventListener('input', render);
  calc.addEventListener('submit', (e) => e.preventDefault());
  syncModes(checked('calc-type'));
  render();
});
