/* Страница «Продукты»: пример «покупка или аренда» (RaaS), выбор продукта в форме, счётчик разделов над тёмной сценой.
   Подключается и на «Услугах» (services.html): там нет калькулятора, работают только data-pick и счётчик над сценой.
   Появление блоков, сам счётчик и форма заявки живут в solutions.js. */
(window.i18n ? window.i18n.ready : Promise.resolve()).then(() => {
  'use strict';
  /* i18n:ru begin (generated by tools/i18n/embed.mjs from i18n/ru.json: the Russian text of the messages this script shows; do not edit) */
  const RU = (() => {
    const nf = new Intl.NumberFormat('ru', { useGrouping: 'always' });
    const n = (x, d) => (d === undefined ? nf : new Intl.NumberFormat('ru', { useGrouping: 'always', minimumFractionDigits: d, maximumFractionDigits: d })).format(x);
    const pr = new Intl.PluralRules('ru');
    const p = (x, o) => o[pr.select(x)] || o.other;
    return {
      n,
      m: {
        'js.products.calc.mln': (v) => `${n(v.n, 1)}\u00a0млн\u00a0₽`,
        'js.products.calc.months': (v) => `${n(v.n)}\u00a0мес.`,
        'js.products.calc.thouPerMonth': (v) => `${n(v.n)}\u00a0тыс.\u00a0₽/мес`,
        'js.products.calc.verdict.always': () => 'При этих условиях аренда дешевле покупки на любом сроке до 5 лет.',
        'js.products.calc.verdict.rent': (v) => `Аренда дешевле покупки на ${n(v.diff, 1)}\u00a0млн\u00a0₽. Расходы сравняются через ${p(v.cross, { one: `${n(v.cross)} месяц`, few: `${n(v.cross)} месяца`, many: `${n(v.cross)} месяцев`, other: `${n(v.cross)} месяца` })}.`,
        'js.products.calc.verdict.buy': (v) => `Покупка выгоднее на ${n(v.diff, 1)}\u00a0млн\u00a0₽: она обогнала аренду после ${p(v.cross, { one: `${n(v.cross)} месяца`, few: `${n(v.cross)} месяцев`, many: `${n(v.cross)} месяцев`, other: `${n(v.cross)} месяца` })}.`,
      },
    };
  })();
  // N: a number as the site writes it in the current language; t: a message, English from the dictionary, else Russian from RU
  const N = (x, d) => (i18n.n || RU.n)(x, d);
  const t = (key, v) => { const s = i18n.t(key, v); return s === undefined ? RU.m[key](v) : s; };
  /* i18n:ru end */

  const $ = (s) => document.querySelector(s);
  const NS = 'http://www.w3.org/2000/svg';
  const node = (tag, attrs = {}, text) => {
    const el = document.createElementNS(NS, tag);
    for (const [k, v] of Object.entries(attrs)) el.setAttribute(k, v);
    if (text !== undefined) el.textContent = text;
    return el;
  };

  // ---------- Расходы владения: сервис 8% + расходники и доля оператора ≈ 8%, итого 16% цены в год (roi-model.js, K) ----------
  const OWN_RATE = 0.16;
  const HORIZON = 60; // месяцев, как срок службы в ROI-калькуляторе

  // ---------- Покупка или аренда ----------
  const el = {
    price: $('#in-price'), rent: $('#in-rent'), term: $('#in-term'),
    oPrice: $('#out-price'), oRent: $('#out-rent'), oTerm: $('#out-term'),
    oBuy: $('#out-buy'), oRentSum: $('#out-rentsum'), verdict: $('#out-verdict'), chart: $('#raas-chart'),
  };
  if (el.chart) {
    const round1 = (x) => Math.round(x * 10) / 10;
    // Всё в млн ₽: покупка = цена + расходы владения × месяцы, аренда = ставка × месяцы
    const model = () => {
      const price = +el.price.value, rent = +el.rent.value / 1000, term = +el.term.value;
      const own = price * OWN_RATE / 12;
      const buy = (m) => price + own * m;
      const rented = (m) => rent * m;
      const gap = rent - own; // на сколько аренда в месяц дороже владения
      const cross = gap > 0 ? price / gap : Infinity;
      return { price, rent, term, buy, rented, cross };
    };

    const W = 560, H = 240, L = 40, R = 12, T = 22, B = 28;
    const draw = (m) => {
      const top = Math.max(m.buy(HORIZON), m.rented(HORIZON));
      const step = [0.5, 1, 2, 2.5, 5, 10].find((s) => top / s <= 5) || 10;
      const yMax = Math.ceil(top / step) * step;
      const x = (mo) => L + (mo / HORIZON) * (W - L - R);
      const y = (v) => H - B - (v / yMax) * (H - B - T);
      const svg = el.chart;
      svg.replaceChildren();
      for (let v = 0; v <= yMax + 1e-9; v += step) {
        svg.append(node('line', { class: 'grid', x1: L, x2: W - R, y1: y(v), y2: y(v) }));
        svg.append(node('text', { class: 'tick', x: L - 8, y: y(v) + 4, 'text-anchor': 'end' }, N(round1(v))));
      }
      svg.append(node('text', { class: 'tick', x: L, y: 12 }, t('js.products.calc.mln', { n: yMax })));
      for (let mo = 0; mo <= HORIZON; mo += 12) {
        svg.append(node('text', { class: 'tick', x: x(mo), y: H - 8, 'text-anchor': mo === 0 ? 'start' : mo === HORIZON ? 'end' : 'middle' }, N(mo)));
      }
      svg.append(node('line', { class: 'term', x1: x(m.term), x2: x(m.term), y1: T - 6, y2: H - B }));
      svg.append(node('path', { class: 'ln ln--buy', d: `M${x(0)} ${y(m.buy(0))}L${x(HORIZON)} ${y(m.buy(HORIZON))}` }));
      svg.append(node('path', { class: 'ln ln--rent', d: `M${x(0)} ${y(0)}L${x(HORIZON)} ${y(m.rented(HORIZON))}` }));
      svg.append(node('circle', { class: 'dot--buy', cx: x(m.term), cy: y(m.buy(m.term)), r: 5 }));
      svg.append(node('circle', { class: 'dot--rent', cx: x(m.term), cy: y(m.rented(m.term)), r: 5 }));
      if (m.cross <= HORIZON) {
        const cx = x(m.cross), cy = y(m.buy(m.cross));
        svg.append(node('circle', { class: 'cross', cx, cy, r: 6 }));
        const right = cx < W * 0.6;
        svg.append(node('text', { class: 'hl', x: right ? cx + 12 : cx - 12, y: cy + 22, 'text-anchor': right ? 'start' : 'end' }, t('js.products.calc.months', { n: Math.round(m.cross) })));
      }
    };

    const fill = (input) => { input.style.setProperty('--p', `${((+input.value - +input.min) / (+input.max - +input.min)) * 100}%`); };

    const update = () => {
      const m = model();
      [el.price, el.rent, el.term].forEach(fill);
      el.oPrice.textContent = t('js.products.calc.mln', { n: m.price });
      el.oRent.textContent = t('js.products.calc.thouPerMonth', { n: +el.rent.value });
      el.oTerm.textContent = t('js.products.calc.months', { n: m.term });
      el.price.setAttribute('aria-valuetext', el.oPrice.textContent);
      el.rent.setAttribute('aria-valuetext', el.oRent.textContent);
      el.term.setAttribute('aria-valuetext', el.oTerm.textContent);
      const buy = m.buy(m.term), rented = m.rented(m.term);
      el.oBuy.textContent = t('js.products.calc.mln', { n: round1(buy) });
      el.oRentSum.textContent = t('js.products.calc.mln', { n: round1(rented) });
      const diff = round1(Math.abs(buy - rented));
      if (m.cross > HORIZON) el.verdict.textContent = t('js.products.calc.verdict.always');
      else if (m.term < m.cross) el.verdict.textContent = t('js.products.calc.verdict.rent', { diff, cross: Math.round(m.cross) });
      else el.verdict.textContent = t('js.products.calc.verdict.buy', { diff, cross: Math.round(m.cross) });
      draw(m);
    };
    [el.price, el.rent, el.term].forEach((i) => i.addEventListener('input', update));
    update();
  }

  // ---------- CTA «Узнать про платформу / аренду / Retrofit»: подставляем продукт в форму ----------
  const select = document.getElementById('f-dir');
  document.addEventListener('click', (e) => {
    const a = e.target.closest && e.target.closest('[data-pick]');
    if (a && select) select.value = a.getAttribute('data-pick');
  });

  // ---------- Счётчик разделов: над тёмной сценой цифры светлые ----------
  const counter = document.querySelector('.counter');
  const dark = [...document.querySelectorAll('[data-dark]')];
  if (counter && dark.length) {
    const sync = () => {
      const r = counter.getBoundingClientRect(), mid = r.top + r.height / 2;
      counter.classList.toggle('on-dark', dark.some((s) => { const b = s.getBoundingClientRect(); return b.top <= mid && b.bottom >= mid; }));
    };
    addEventListener('scroll', sync, { passive: true });
    addEventListener('resize', sync);
    sync();
  }
});
